apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    access: proxy
    uid: jaeger
    url: http://jaeger:16686
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags: [{ key: trace_id }]
        spanStartTimeShift: '-2m'
        spanEndTimeShift: '2m'
        filterByTraceID: true

  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"([0-9a-f]+)"'
          url: '$${__value.raw}'
          datasourceUid: jaeger

  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
